//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmDBV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int TransactionID { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string TransactionDescription { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<int> AccountNumber1 { get; set; }
        public Nullable<decimal> Account1Amount { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
